### ISSUE TITLE
fortran/install.py  report error  at line 49

### ISSUE THREAD

**Issue by irreallich** [ycm-core/lsp-examples#10]
when I try to run "python install.py --enable-fortran" , it report fail.
It failed at line 49 of file fortran/install.py 
    subprocess.check_call( [ pip, 'install', 'fortran-language-server' ] )

I try to change the code as the following, it is  worked .
    subprocess.check_call( [ 'pip', 'install', 'fortran-language-server' ] )

I hop it is useful .

**Comment by bstaletic** [comment]
```python
def Main():
  npm = FindExecutableOrDie( 'pip', 'pip is required to install fortls.' )
  subprocess.check_call( [ pip, 'install', 'fortran-language-server' ] )
```

Yeah... that `npm =` should have been `pip =`. I already applied the change to master. Thanks for the report.
