### ISSUE TITLE
build.py: error: unrecognized arguments --enable-rust

### ISSUE THREAD

**Issue by GreenMine** [ycm-core/lsp-examples#15]
My steps:
1. insatll rust-analyzer bin
2. git clone https://github.com/ycm-core/YouCompleteMe
3. git submodule update --init --recursive
4. ./install.py --enable-rust
I got: build.py: error: unrecognized arguments --enable-rust

**Comment by bstaletic** [comment]
Interesting... What's the output of `./install.py --help | grep rust`? Also what's the output of `git rev-parse HEAD`?

**Comment by GreenMine** [comment]
1.[--go-completer] [--rust-completer] [--java-completer]
  --rust-completer      Enable Rust semantic completion engine.
2. 195f730dfb4d818a81082b383e294a302f61bcfe

**Comment by bstaletic** [comment]
lsp-examples has its own `install.py`. You should run that one and pass it `--enable-rust`.
