### ISSUE TITLE
dartfmt is being deprecated

### ISSUE THREAD

**Issue by Barabas5532** [ycm-core/lsp-examples#28]
I'm trying to set up Dart to use with Flutter. My Flutter version is:

```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (2 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

`python3 ./install.py --enable-dart` fails because `dartfmt` is not in my path:

```
*** Entering direcory /home/barabas/.vim/ycm-lsp-examples/dart ***
Traceback (most recent call last):
  File "/home/barabas/.vim/ycm-lsp-examples/dart/install.py", line 38, in <module>
    raise UserWarning( '`dart` and `dartfmt` are needed in $PATH for proper operation' )
UserWarning: `dart` and `dartfmt` are needed in $PATH for proper operation
** FAILED **: dart
```

According to https://github.com/dart-lang/dart_style/issues/986, `dartfmt` is being replaced by `dart format`. The latter works on my install. 

I think the installer should check for both `dart format` and `dartfmt` to check if the formatter is installed.

----

After some more investigation I think `dartfmt` is not required at all. It is only mentioned in the installer, unless it is used internally by the language server?

**Comment by puremourning** [comment]
Thanks for the report. Are you happy to make a PR to resolve this? This is mostly a community-maintained repo. I have no clue what dartfmt or dart format are and/or whather the dart language server requires them. It could well be that this has changed since dart was added to this repo.
