### ISSUE TITLE
Dart completer broken after flutter update

### ISSUE THREAD

**Issue by Barabas5532** [ycm-core/lsp-examples#31]
After full system update (Arch Linux with [AUR package](https://aur.archlinux.org/packages/flutter)), dart completion is no longer working.

Flutter doctor is clean, and flutter CLI (including `flutter format`) is working fine.

```
Printing YouCompleteMe debug information...
-- Resolve completions: Up front
-- Client logfile: /tmp/ycm_lyxq56r9.log
-- Server Python interpreter: /usr/bin/python
-- Server Python version: 3.10.2
-- Server has Clang support compiled in: False
-- Clang version: None
-- Extra configuration file found and loaded
-- Extra configuration path: /home/barabas/.vim/.ycm_extra_conf.py
-- GenericLSP completer debug information:
--   dartCompleter not running
--   dartCompleter executable: ['/opt/flutter/bin/dart', '/home/barabas/.vim/ycm-lsp-examples/dart/analysis_server.dart.snapshot', '--lsp']
--   dartCompleter logfiles:
--     /tmp/dartcompleter_stderr98f8btlb.log
--   dartCompleter Server State: Dead
--   dartCompleter Project Directory: /home/barabas/projects/hardware/guitar_dsp_platform/monorepo/core/frontend
--   dartCompleter Settings: {}
-- Server running at: http://127.0.0.1:41457
-- Server process ID: 64508
-- Server logfiles:
--   /tmp/ycmd_41457_stdout_72iqrnja.log
--   /tmp/ycmd_41457_stderr_vjhn6w6h.log
```

The dartcompleter logs show this:
`Wrong full snapshot version, expected 'd56742caf7b3b3f4bd2df93a9bbb5503' found 'adf563436d12ba0d50ea5beb7f3be1bb'`

**Comment by Barabas5532** [comment]
Fixed after re-running `install.py`.

Looks like there is a magic number that has to match between the system version of dart and the loaded snapshots.

```
$ cat dart-sdk/version
2.16.1

$ flutter --version
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (2 weeks ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

$ grep -r d5674 .
grep: ./dart-sdk/bin/utils/gen_snapshot: binary file matches
grep: ./dart-sdk/bin/dartaotruntime: binary file matches
grep: ./dart-sdk/bin/dart: binary file matches
grep: ./dart-sdk/bin/snapshots/gen_kernel.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/kernel-service.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/dart2js.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/dartdoc.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/dartdev.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/analysis_server.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/dartanalyzer.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/dds.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/kernel_worker.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/frontend_server.dart.snapshot: binary file matches
grep: ./dart-sdk/bin/snapshots/dartdevc.dart.snapshot: binary file matches
```

**Comment by Barabas5532** [comment]
I think the `analysis_server.dart.snapshot` should actually always exist on the system if `dart` is installed. Currently the latest version is downloaded by `install.py`, which probably won't work if the system is not using the latest version of `dart`.

Using the system version of the server should resolve this issue.

**Comment by Barabas5532** [comment]
https://github.com/natebosch/vim-lsc-dart uses the system server:

https://github.com/natebosch/vim-lsc-dart/blob/e2dc59f71282735d2eb05d6487d2e1db09a9d77b/autoload/lsc/dart.vim#L70

**Comment by puremourning** [comment]
I'm not sure what you're expecting us to do about this? I mean we're not going to spend time maintaining some random dependencies of niche languages...

AFAICT the "install" script for the dart sdk uses the 'stable' version: `ARCHIVE_URL = 'https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-{}-{}-release.zip'`

I guess your choices are:

- upgrade "dart" or "flutter" or whatever
- downgrade the dart sdk in the install.py, or just put a working copy of analysis_server.dart.snapshot in dart/
- use g:ycm_language_server to point to any working copy of analysis_server of your choice.

This repo is supposed to be helpful and low maintenance; we do not provide extended support.

**Comment by Barabas5532** [comment]
Found a simple workaround. Instead of including the `snippet.vim` provided, we can define the `g:ycm_language_server` like this:

```
let g:ycm_language_server = [
  \   {
  \     'name': 'dart',
  \     'cmdline': [ 'dart', '/opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot', '--lsp' ],
  \     'filetypes': [ 'dart' ],
  \   },
  \ ]
```

I don't expect any support, just wanted to make a note so that anyone else that runs into this issue will find my solution.
