### ISSUE TITLE
Reported error for comment after an indented let=<<

### ISSUE THREAD

**Issue by Aster89** [ycm-core/lsp-examples#33]
Well, I too hurriedly posted this issue on Vim, https://github.com/vim/vim/issues/11642, but in reality it belongs here. Below is a copy of the text.

### Steps to reproduce

1. Open a vimscript file and fill it with the following content:
```viml
fun SomeFun()
  let text =<< trim END
  Some text
  END
endf
" a comment
```
2. Observe the syntax coloring of `"`
3. Hit <kbd>Escape</kbd><kbd>G</kbd><kbd>A</kbd><kbd>Enter</kbd><kbd>Enter</kbd>.
4. See the error.

Here's a screencast:

[![asciicast](https://asciinema.org/a/t9eVPrfsP6CAAJwo4AiaLUKkL.svg)](https://asciinema.org/a/t9eVPrfsP6CAAJwo4AiaLUKkL)

---

Note there's nothing after the closing `END` and there's as much space before as before `let`. This is consistent with [`let {var-name} =<< [trim] [eval] {endmarker}`'s documentation](https://vimhelp.org/eval.txt.html#%3Alet%3D%3C%3C), specifically

> The last line should end only with the `{endmarker}` string without any other character.

and
> The marker must line up with "`let`".

### Expected behaviour

Correct syntax coloring and no error.

### Version of Vim

9.0 patch 1-910

### Environment

Operating system: up-to-date Archlinux
Terminal: URxvt
Value of $TERM: rxvt-unicode-256color
Shell: Bash

**Comment by puremourning** [comment]
this repo is just a way to install some language servers, it does not have any actual functionality so can't possibly be the cause of whatever your issue is.
