### ISSUE TITLE
Scope of this project?

### ISSUE THREAD

**Issue by simlei** [ycm-core/lsp-examples#4]
Hi, 

I am quite interested in the general direction of this project;
I have read the relevant discussion at https://github.com/ycm-core/ycmd/issues/515 .

Is this implementing a way for ycmd to wrap around LSP? Could you give a short outline of how it is implemented? How is the general philosophy of which LS features are supported? (I assume to be minimal for this initial effort)

Thanks :)

**Comment by puremourning** [comment]
YCM/ycmd support arbitrary language servers, via [the `g:ycm_language_server` option](https://github.com/ycm-core/YouCompleteMe#plugging-an-arbitrary-lsp-server). 

This repo is simply a place where we put some language servers and [how to tell ycm to use them](https://github.com/ycm-core/lsp-examples#quick-start) without officially or fully supporting them in ycmd itself.

**Comment by puremourning** [comment]
FWIW we still have absolutely _no intention_ to support a LSP interface to ycmd.
